FROM python:3.9

WORKDIR /home
RUN apt-get update
RUN apt-get install -y git

RUN git clone https://github.com/googleapis/python-pubsub.git
WORKDIR /home/python-pubsub/samples/snippets/
RUN pip install -r requirements.txt
